name: CI

on:
  push:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 17.x
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test

  test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Go dependencies
      run: |
        ls -la
        cd ./services
        go mod download

    - name: Test Go
      run: go test ./...

